# Cyberdream: dark / light, a high-contrast futuristic theme. Palette values copied from
# cyberdream.nvim (lua/cyberdream/colors.lua); terminal colours from its official kitty extras
# (cyberdream.conf, cyberdream-light.conf).
# Source: https://github.com/scottmckendry/cyberdream.nvim  License: MIT  Copyright: Scott McKendry

[meta]
family = "cyberdream"
name = "Cyberdream"
source = "https://github.com/scottmckendry/cyberdream.nvim"
license = "MIT"

[dark.ui]
bg = "#16181a"
bg_alt = "#1e2124"
surface = "#1e2124"
overlay = "#3c4048"
fg = "#ffffff"
fg_muted = "#7b8496"
primary = "#5ea1ff"
on_primary = "#16181a"
secondary = "#bd5eff"
accent = "#ffbd5e"
success = "#5eff6c"
warning = "#f1ff5e"
error = "#ff6e5e"
border = "#3c4048"
border_active = "#5ef1ff"
selection = "#3c4048"

[dark.ansi]
c0 = "#16181a"
c1 = "#ff6e5e"
c2 = "#5eff6c"
c3 = "#f1ff5e"
c4 = "#5ea1ff"
c5 = "#bd5eff"
c6 = "#5ef1ff"
c7 = "#ffffff"
c8 = "#3c4048"
c9 = "#ff6e5e"
c10 = "#5eff6c"
c11 = "#f1ff5e"
c12 = "#5ea1ff"
c13 = "#bd5eff"
c14 = "#5ef1ff"
c15 = "#ffffff"

[light.ui]
bg = "#ffffff"
bg_alt = "#eaeaea"
surface = "#eaeaea"
overlay = "#acacac"
fg = "#16181a"
fg_muted = "#7b8496"
primary = "#0057d1"
on_primary = "#ffffff"
secondary = "#a018ff"
accent = "#d17c00"
success = "#008b0c"
warning = "#997b00"
error = "#d11500"
border = "#acacac"
border_active = "#008c99"
selection = "#acacac"

[light.ansi]
c0 = "#ffffff"
c1 = "#d11500"
c2 = "#008b0c"
c3 = "#997b00"
c4 = "#0057d1"
c5 = "#a018ff"
c6 = "#008c99"
c7 = "#16181a"
c8 = "#acacac"
c9 = "#d11500"
c10 = "#008b0c"
c11 = "#997b00"
c12 = "#0057d1"
c13 = "#a018ff"
c14 = "#008c99"
c15 = "#16181a"
