# E-ink: greyscale dark / light for monochrome wallpapers. Palette values copied from e-ink.nvim
# (16-step mono ramp; error red is the everforest red e-ink.nvim uses for diagnostics).
# Source: https://github.com/alexxGmZ/e-ink.nvim  License: MIT  Copyright: Algilbert Gomez

[meta]
family = "eink"
name = "E-ink"
source = "https://github.com/alexxGmZ/e-ink.nvim"
license = "MIT"
nvim_dark = "e-ink"
nvim_light = "e-ink"

[dark.ui]
bg = "#333333"
bg_alt = "#474747"
surface = "#4a4a4a"
overlay = "#5e5e5e"
fg = "#c2c2c2"
fg_muted = "#909090"
primary = "#cccccc"
on_primary = "#333333"
secondary = "#aeaeae"
accent = "#a4a4a4"
success = "#aeaeae"
warning = "#cccccc"
error = "#e67e80"
border = "#545454"
border_active = "#a4a4a4"
selection = "#545454"

[dark.ansi]
c0 = "#474747"
c1 = "#e67e80"
c2 = "#a4a4a4"
c3 = "#b8b8b8"
c4 = "#9a9a9a"
c5 = "#aeaeae"
c6 = "#909090"
c7 = "#c2c2c2"
c8 = "#7c7c7c"
c9 = "#e67e80"
c10 = "#aeaeae"
c11 = "#c2c2c2"
c12 = "#a4a4a4"
c13 = "#b8b8b8"
c14 = "#9a9a9a"
c15 = "#cccccc"

[light.ui]
bg = "#cccccc"
bg_alt = "#c2c2c2"
surface = "#b8b8b8"
overlay = "#a4a4a4"
fg = "#333333"
fg_muted = "#686868"
primary = "#333333"
on_primary = "#cccccc"
secondary = "#545454"
accent = "#5e5e5e"
success = "#545454"
warning = "#333333"
error = "#f85552"
border = "#aeaeae"
border_active = "#5e5e5e"
selection = "#aeaeae"

[light.ansi]
c0 = "#c2c2c2"
c1 = "#f85552"
c2 = "#5e5e5e"
c3 = "#4a4a4a"
c4 = "#686868"
c5 = "#545454"
c6 = "#727272"
c7 = "#474747"
c8 = "#868686"
c9 = "#f85552"
c10 = "#545454"
c11 = "#474747"
c12 = "#5e5e5e"
c13 = "#4a4a4a"
c14 = "#686868"
c15 = "#333333"
