# Flexoki: dark / light, "an inky colour scheme for prose and code". Palette values copied from the
# Flexoki README (base and accent scales, dark/light theme mapping); terminal colours from its
# official kitty themes (flexoki_dark.conf, flexoki_light.conf).
# Source: https://github.com/kepano/flexoki  License: MIT  Copyright: Steph Ango

[meta]
family = "flexoki"
name = "Flexoki"
source = "https://github.com/kepano/flexoki"
license = "MIT"

[dark.ui]
bg = "#100f0f"
bg_alt = "#1c1b1a"
surface = "#282726"
overlay = "#343331"
fg = "#cecdc3"
fg_muted = "#878580"
primary = "#4385be"
on_primary = "#100f0f"
secondary = "#8b7ec8"
accent = "#da702c"
success = "#879a39"
warning = "#d0a215"
error = "#d14d41"
border = "#343331"
border_active = "#575653"
selection = "#403e3c"

[dark.ansi]
c0 = "#100f0f"
c1 = "#af3029"
c2 = "#66800b"
c3 = "#ad8301"
c4 = "#205ea6"
c5 = "#a02f6f"
c6 = "#24837b"
c7 = "#878580"
c8 = "#6f6e69"
c9 = "#d14d41"
c10 = "#879a39"
c11 = "#d0a215"
c12 = "#4385be"
c13 = "#ce5d97"
c14 = "#3aa99f"
c15 = "#cecdc3"

[light.ui]
bg = "#fffcf0"
bg_alt = "#f2f0e5"
surface = "#e6e4d9"
overlay = "#dad8ce"
fg = "#100f0f"
fg_muted = "#6f6e69"
primary = "#205ea6"
on_primary = "#fffcf0"
secondary = "#5e409d"
accent = "#bc5215"
success = "#66800b"
warning = "#ad8301"
error = "#af3029"
border = "#dad8ce"
border_active = "#b7b5ac"
selection = "#cecdc3"

[light.ansi]
c0 = "#100f0f"
c1 = "#d14d41"
c2 = "#879a39"
c3 = "#d0a215"
c4 = "#4385be"
c5 = "#ce5d97"
c6 = "#3aa99f"
c7 = "#fffcf0"
c8 = "#6f6e69"
c9 = "#af3029"
c10 = "#66800b"
c11 = "#ad8301"
c12 = "#205ea6"
c13 = "#a02f6f"
c14 = "#24837b"
c15 = "#f2f0e5"
