# Gruvbox: dark (dark) / light (light). Palette values copied from the official ports.
# Source: https://github.com/ellisonleao/gruvbox.nvim  License: MIT  Copyright: Pavel Pertsev, ellisonleao

[meta]
family = "gruvbox"
name = "Gruvbox"
source = "https://github.com/ellisonleao/gruvbox.nvim"
license = "MIT"

[dark.ui]
bg = "#282828"
bg_alt = "#1d2021"
surface = "#3c3836"
overlay = "#504945"
fg = "#ebdbb2"
fg_muted = "#a89984"
primary = "#fabd2f"
on_primary = "#282828"
secondary = "#8ec07c"
accent = "#fe8019"
success = "#b8bb26"
warning = "#fabd2f"
error = "#fb4934"
border = "#504945"
border_active = "#fabd2f"
selection = "#504945"

[dark.ansi]
c0 = "#3c3836"
c1 = "#cc241d"
c2 = "#98971a"
c3 = "#d79921"
c4 = "#458588"
c5 = "#b16286"
c6 = "#689d6a"
c7 = "#a89984"
c8 = "#928374"
c9 = "#fb4934"
c10 = "#b8bb26"
c11 = "#fabd2f"
c12 = "#83a598"
c13 = "#d3869b"
c14 = "#8ec07c"
c15 = "#fbf1c7"

[light.ui]
bg = "#fbf1c7"
bg_alt = "#f9f5d7"
surface = "#ebdbb2"
overlay = "#d5c4a1"
fg = "#3c3836"
fg_muted = "#7c6f64"
primary = "#b57614"
on_primary = "#fbf1c7"
secondary = "#427b58"
accent = "#af3a03"
success = "#79740e"
warning = "#b57614"
error = "#9d0006"
border = "#d5c4a1"
border_active = "#b57614"
selection = "#d5c4a1"

[light.ansi]
c0 = "#ebdbb2"
c1 = "#cc241d"
c2 = "#98971a"
c3 = "#d79921"
c4 = "#458588"
c5 = "#b16286"
c6 = "#689d6a"
c7 = "#7c6f64"
c8 = "#928374"
c9 = "#9d0006"
c10 = "#79740e"
c11 = "#b57614"
c12 = "#076678"
c13 = "#8f3f71"
c14 = "#427b58"
c15 = "#282828"
