# Kanagawa: wave (dark) / lotus (light). Palette values copied from kanagawa.nvim (lua/kanagawa/
# colors.lua); terminal colours from its official kitty extras (kanagawa.conf, kanagawa_light.conf).
# Source: https://github.com/rebelot/kanagawa.nvim  License: MIT  Copyright: Tommaso Laurenzi

[meta]
family = "kanagawa"
name = "Kanagawa"
source = "https://github.com/rebelot/kanagawa.nvim"
license = "MIT"

[dark.ui]
bg = "#1f1f28"
bg_alt = "#16161d"
surface = "#2a2a37"
overlay = "#363646"
fg = "#dcd7ba"
fg_muted = "#727169"
primary = "#7e9cd8"
on_primary = "#1f1f28"
secondary = "#957fb8"
accent = "#ffa066"
success = "#98bb6c"
warning = "#e6c384"
error = "#e46876"
border = "#54546d"
border_active = "#7e9cd8"
selection = "#2d4f67"

[dark.ansi]
c0 = "#16161d"
c1 = "#c34043"
c2 = "#76946a"
c3 = "#c0a36e"
c4 = "#7e9cd8"
c5 = "#957fb8"
c6 = "#6a9589"
c7 = "#c8c093"
c8 = "#727169"
c9 = "#e82424"
c10 = "#98bb6c"
c11 = "#e6c384"
c12 = "#7fb4ca"
c13 = "#938aa9"
c14 = "#7aa89f"
c15 = "#dcd7ba"

[light.ui]
bg = "#f2ecbc"
bg_alt = "#e5ddb0"
surface = "#dcd5ac"
overlay = "#d5cea3"
fg = "#545464"
fg_muted = "#716e61"
primary = "#4d699b"
on_primary = "#f2ecbc"
secondary = "#624c83"
accent = "#cc6d00"
success = "#6f894e"
warning = "#de9800"
error = "#c84053"
border = "#a09cac"
border_active = "#4d699b"
selection = "#c9cbd1"

[light.ansi]
c0 = "#1f1f28"
c1 = "#c84053"
c2 = "#6f894e"
c3 = "#77713f"
c4 = "#4d699b"
c5 = "#b35b79"
c6 = "#597b75"
c7 = "#545464"
c8 = "#8a8980"
c9 = "#d7474b"
c10 = "#6e915f"
c11 = "#836f4a"
c12 = "#6693bf"
c13 = "#624c83"
c14 = "#5e857a"
c15 = "#43436c"
