# Tokyo Night: night (dark) / day (light). Palette values copied from the official ports.
# Source: https://github.com/folke/tokyonight.nvim  License: Apache-2.0  Copyright: Folke Lemaitre

[meta]
family = "tokyonight"
name = "Tokyo Night"
source = "https://github.com/folke/tokyonight.nvim"
license = "Apache-2.0"
nvim_dark = "tokyonight-night"
nvim_light = "tokyonight-day"

[dark.ui]
bg = "#1a1b26"
bg_alt = "#16161e"
surface = "#292e42"
overlay = "#3b4261"
fg = "#c0caf5"
fg_muted = "#737aa2"
primary = "#7aa2f7"
on_primary = "#1a1b26"
secondary = "#bb9af7"
accent = "#ff9e64"
success = "#9ece6a"
warning = "#e0af68"
error = "#f7768e"
border = "#3b4261"
border_active = "#7aa2f7"
selection = "#283457"

[dark.ansi]
c0 = "#15161e"
c1 = "#f7768e"
c2 = "#9ece6a"
c3 = "#e0af68"
c4 = "#7aa2f7"
c5 = "#bb9af7"
c6 = "#7dcfff"
c7 = "#a9b1d6"
c8 = "#414868"
c9 = "#ff899d"
c10 = "#9fe044"
c11 = "#faba4a"
c12 = "#8db0ff"
c13 = "#c7a9ff"
c14 = "#a4daff"
c15 = "#c0caf5"

[light.ui]
bg = "#e1e2e7"
bg_alt = "#d0d5e3"
surface = "#c4c8da"
overlay = "#a8aecb"
fg = "#3760bf"
fg_muted = "#68709a"
primary = "#2e7de9"
on_primary = "#e1e2e7"
secondary = "#9854f1"
accent = "#b15c00"
success = "#587539"
warning = "#8c6c3e"
error = "#f52a65"
border = "#a8aecb"
border_active = "#2e7de9"
selection = "#b7c1e3"

[light.ansi]
c0 = "#b4b5b9"
c1 = "#f52a65"
c2 = "#587539"
c3 = "#8c6c3e"
c4 = "#2e7de9"
c5 = "#9854f1"
c6 = "#007197"
c7 = "#6172b0"
c8 = "#a1a6c5"
c9 = "#ff4774"
c10 = "#5c8524"
c11 = "#a27629"
c12 = "#358aff"
c13 = "#a463ff"
c14 = "#007ea8"
c15 = "#3760bf"
