-- Generated by theme_render.py ($family $mode); edit the theme or this template, not the output.
-- Read by ~/.config/nvim/colors/desktop.lua (mini.base16) at startup and on SIGUSR1 from `theme`.
return {
	background = "$mode",
	palette = {
		base00 = "$bg", base01 = "$surface", base02 = "$selection", base03 = "$fg_muted",
		base04 = "$fg_muted", base05 = "$fg", base06 = "$fg", base07 = "$fg",
		base08 = "$error", base09 = "$accent", base0A = "$warning", base0B = "$success",
		base0C = "$c6", base0D = "$primary", base0E = "$secondary", base0F = "$c9",
	},
}
