" Generated by theme_render.py ($family $mode); edit the theme or this template, not the output.
" Sourced by ~/.vimrc at startup and whenever it changes. Backgrounds stay transparent.
set background=$mode
highlight clear
if exists('syntax_on') | syntax reset | endif
let g:colors_name = 'desktop'

hi Normal       guifg=$fg guibg=NONE
hi NonText      guifg=$overlay guibg=NONE
hi EndOfBuffer  guifg=$bg guibg=NONE
hi LineNr       guifg=$overlay guibg=NONE
hi CursorLineNr guifg=$primary guibg=NONE gui=bold
hi SignColumn   guibg=NONE
hi FoldColumn   guifg=$overlay guibg=NONE
hi Folded       guifg=$fg_muted guibg=$surface
hi CursorLine   guibg=$surface gui=NONE cterm=NONE
hi CursorColumn guibg=$surface
hi ColorColumn  guibg=$surface
hi Visual       guibg=$selection
hi Search       guifg=$on_primary guibg=$warning
hi IncSearch    guifg=$on_primary guibg=$accent
hi CurSearch    guifg=$on_primary guibg=$accent
hi MatchParen   guifg=$accent guibg=NONE gui=bold
hi VertSplit    guifg=$border guibg=NONE gui=NONE
hi WinSeparator guifg=$border guibg=NONE
hi StatusLine   guifg=$fg guibg=$surface gui=NONE
hi StatusLineNC guifg=$fg_muted guibg=NONE gui=NONE
hi TabLine      guifg=$fg_muted guibg=NONE gui=NONE
hi TabLineFill  guibg=NONE gui=NONE
hi TabLineSel   guifg=$primary guibg=NONE gui=bold
hi Pmenu        guifg=$fg guibg=$surface
hi PmenuSel     guifg=$on_primary guibg=$primary
hi PmenuSbar    guibg=$surface
hi PmenuThumb   guibg=$overlay
hi WildMenu     guifg=$on_primary guibg=$primary
hi Directory    guifg=$primary
hi Title        guifg=$primary gui=bold
hi ErrorMsg     guifg=$error guibg=NONE
hi WarningMsg   guifg=$warning
hi ModeMsg      guifg=$success gui=bold
hi MoreMsg      guifg=$success
hi Question     guifg=$primary
hi SpecialKey   guifg=$overlay
hi DiffAdd      guifg=$success guibg=NONE
hi DiffChange   guifg=$warning guibg=NONE
hi DiffDelete   guifg=$error guibg=NONE
hi DiffText     guifg=$primary guibg=NONE gui=bold
hi SpellBad     gui=undercurl guisp=$error
hi SpellCap     gui=undercurl guisp=$warning

hi Comment      guifg=$fg_muted gui=italic
hi Constant     guifg=$accent
hi String       guifg=$success
hi Character    guifg=$success
hi Number       guifg=$accent
hi Boolean      guifg=$accent
hi Identifier   guifg=$c6 gui=NONE
hi Function     guifg=$primary
hi Statement    guifg=$secondary gui=NONE
hi Operator     guifg=$c6
hi PreProc      guifg=$secondary
hi Type         guifg=$warning gui=NONE
hi Special      guifg=$c6
hi Delimiter    guifg=$fg_muted
hi Underlined   guifg=$primary gui=underline
hi Error        guifg=$error guibg=NONE
hi Todo         guifg=$on_primary guibg=$warning gui=bold
