" Generated by theme_render.py (rosepine dark); edit the theme or this template, not the output.
" Sourced by ~/.vimrc at startup and whenever it changes. Backgrounds stay transparent.
set background=dark
highlight clear
if exists('syntax_on') | syntax reset | endif
let g:colors_name = 'desktop'

hi Normal       guifg=#e0def4 guibg=NONE
hi NonText      guifg=#403d52 guibg=NONE
hi EndOfBuffer  guifg=#191724 guibg=NONE
hi LineNr       guifg=#403d52 guibg=NONE
hi CursorLineNr guifg=#c4a7e7 guibg=NONE gui=bold
hi SignColumn   guibg=NONE
hi FoldColumn   guifg=#403d52 guibg=NONE
hi Folded       guifg=#908caa guibg=#26233a
hi CursorLine   guibg=#26233a gui=NONE cterm=NONE
hi CursorColumn guibg=#26233a
hi ColorColumn  guibg=#26233a
hi Visual       guibg=#403d52
hi Search       guifg=#191724 guibg=#f6c177
hi IncSearch    guifg=#191724 guibg=#ebbcba
hi CurSearch    guifg=#191724 guibg=#ebbcba
hi MatchParen   guifg=#ebbcba guibg=NONE gui=bold
hi VertSplit    guifg=#524f67 guibg=NONE gui=NONE
hi WinSeparator guifg=#524f67 guibg=NONE
hi StatusLine   guifg=#e0def4 guibg=#26233a gui=NONE
hi StatusLineNC guifg=#908caa guibg=NONE gui=NONE
hi TabLine      guifg=#908caa guibg=NONE gui=NONE
hi TabLineFill  guibg=NONE gui=NONE
hi TabLineSel   guifg=#c4a7e7 guibg=NONE gui=bold
hi Pmenu        guifg=#e0def4 guibg=#26233a
hi PmenuSel     guifg=#191724 guibg=#c4a7e7
hi PmenuSbar    guibg=#26233a
hi PmenuThumb   guibg=#403d52
hi WildMenu     guifg=#191724 guibg=#c4a7e7
hi Directory    guifg=#c4a7e7
hi Title        guifg=#c4a7e7 gui=bold
hi ErrorMsg     guifg=#eb6f92 guibg=NONE
hi WarningMsg   guifg=#f6c177
hi ModeMsg      guifg=#9ccfd8 gui=bold
hi MoreMsg      guifg=#9ccfd8
hi Question     guifg=#c4a7e7
hi SpecialKey   guifg=#403d52
hi DiffAdd      guifg=#9ccfd8 guibg=NONE
hi DiffChange   guifg=#f6c177 guibg=NONE
hi DiffDelete   guifg=#eb6f92 guibg=NONE
hi DiffText     guifg=#c4a7e7 guibg=NONE gui=bold
hi SpellBad     gui=undercurl guisp=#eb6f92
hi SpellCap     gui=undercurl guisp=#f6c177

hi Comment      guifg=#908caa gui=italic
hi Constant     guifg=#ebbcba
hi String       guifg=#9ccfd8
hi Character    guifg=#9ccfd8
hi Number       guifg=#ebbcba
hi Boolean      guifg=#ebbcba
hi Identifier   guifg=#ebbcba gui=NONE
hi Function     guifg=#c4a7e7
hi Statement    guifg=#31748f gui=NONE
hi Operator     guifg=#ebbcba
hi PreProc      guifg=#31748f
hi Type         guifg=#f6c177 gui=NONE
hi Special      guifg=#ebbcba
hi Delimiter    guifg=#908caa
hi Underlined   guifg=#c4a7e7 gui=underline
hi Error        guifg=#eb6f92 guibg=NONE
hi Todo         guifg=#191724 guibg=#f6c177 gui=bold
