-- Generated by theme_render.py (tokyonight dark); edit the theme or this template, not the output.
-- Read by ~/.config/nvim/lua/config/theme.lua at startup and on SIGUSR1 (sent by `theme`).
return { colorscheme = "tokyonight-night", background = "dark" }
