" Generated by theme_render.py (tokyonight dark); edit the theme or this template, not the output.
" Sourced by ~/.vimrc at startup and whenever it changes. Backgrounds stay transparent.
set background=dark
highlight clear
if exists('syntax_on') | syntax reset | endif
let g:colors_name = 'desktop'

hi Normal       guifg=#c0caf5 guibg=NONE
hi NonText      guifg=#3b4261 guibg=NONE
hi EndOfBuffer  guifg=#1a1b26 guibg=NONE
hi LineNr       guifg=#3b4261 guibg=NONE
hi CursorLineNr guifg=#7aa2f7 guibg=NONE gui=bold
hi SignColumn   guibg=NONE
hi FoldColumn   guifg=#3b4261 guibg=NONE
hi Folded       guifg=#737aa2 guibg=#292e42
hi CursorLine   guibg=#292e42 gui=NONE cterm=NONE
hi CursorColumn guibg=#292e42
hi ColorColumn  guibg=#292e42
hi Visual       guibg=#283457
hi Search       guifg=#1a1b26 guibg=#e0af68
hi IncSearch    guifg=#1a1b26 guibg=#ff9e64
hi CurSearch    guifg=#1a1b26 guibg=#ff9e64
hi MatchParen   guifg=#ff9e64 guibg=NONE gui=bold
hi VertSplit    guifg=#3b4261 guibg=NONE gui=NONE
hi WinSeparator guifg=#3b4261 guibg=NONE
hi StatusLine   guifg=#c0caf5 guibg=#292e42 gui=NONE
hi StatusLineNC guifg=#737aa2 guibg=NONE gui=NONE
hi TabLine      guifg=#737aa2 guibg=NONE gui=NONE
hi TabLineFill  guibg=NONE gui=NONE
hi TabLineSel   guifg=#7aa2f7 guibg=NONE gui=bold
hi Pmenu        guifg=#c0caf5 guibg=#292e42
hi PmenuSel     guifg=#1a1b26 guibg=#7aa2f7
hi PmenuSbar    guibg=#292e42
hi PmenuThumb   guibg=#3b4261
hi WildMenu     guifg=#1a1b26 guibg=#7aa2f7
hi Directory    guifg=#7aa2f7
hi Title        guifg=#7aa2f7 gui=bold
hi ErrorMsg     guifg=#f7768e guibg=NONE
hi WarningMsg   guifg=#e0af68
hi ModeMsg      guifg=#9ece6a gui=bold
hi MoreMsg      guifg=#9ece6a
hi Question     guifg=#7aa2f7
hi SpecialKey   guifg=#3b4261
hi DiffAdd      guifg=#9ece6a guibg=NONE
hi DiffChange   guifg=#e0af68 guibg=NONE
hi DiffDelete   guifg=#f7768e guibg=NONE
hi DiffText     guifg=#7aa2f7 guibg=NONE gui=bold
hi SpellBad     gui=undercurl guisp=#f7768e
hi SpellCap     gui=undercurl guisp=#e0af68

hi Comment      guifg=#737aa2 gui=italic
hi Constant     guifg=#ff9e64
hi String       guifg=#9ece6a
hi Character    guifg=#9ece6a
hi Number       guifg=#ff9e64
hi Boolean      guifg=#ff9e64
hi Identifier   guifg=#7dcfff gui=NONE
hi Function     guifg=#7aa2f7
hi Statement    guifg=#bb9af7 gui=NONE
hi Operator     guifg=#7dcfff
hi PreProc      guifg=#bb9af7
hi Type         guifg=#e0af68 gui=NONE
hi Special      guifg=#7dcfff
hi Delimiter    guifg=#737aa2
hi Underlined   guifg=#7aa2f7 gui=underline
hi Error        guifg=#f7768e guibg=NONE
hi Todo         guifg=#1a1b26 guibg=#e0af68 gui=bold
