# Replace the "❯" symbol in the prompt with "➜"
[character]      # The name of the module we are configuring is "character"
#symbol = "➜"     # The "symbol" segment is being set to "➜"
# use_symbol_for_status = true  # Show "✖" when the command failed

[custom.shell]
command = "echo $STARSHIP_SHELL"  # shows output of command
when = """ test "$STARSHIP_SHELL" != "fish" """
style = "dimmed blue"
format = "[$output]($style)"
shell =["bash"]

# [custom.neovim]
# command = 'bob ls | rg Used | awk "{print \$2}"'  # shows output of command
# detect_folders = ["lua"]
# style = "green"
# format = "[ $output ]($style)"
# shell =["bash"]


[git_status]
untracked = '[ $count](bold yellow) '
staged = '[ $count](bold green) '
stashed = "[ ](cyan) "
deleted = '[ $count](bold red) '
modified= '[ $count](bold blue) '
behind = '[ ](bold purple) '
ahead = '[ ](bold purple) '
format = '([$all_status$ahead_behind]($style))'

[[battery.display]]
threshold = 50

[lua]
detect_folders = []
symbol = " "

[git_metrics]
disabled = false

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " 󰌾"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = "⌘ "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[pijul_channel]
symbol = "🪺 "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[spack]
symbol = "🅢 "
