color0 #1f2335
color1 #f7768e
color2 #9cd58a
color3 #e6c384
color4 #7a88cf
color5 #d7729f
color6 #7bb0c0
color7 #8289a6
color8 #545c7e
color9 #f7768e
color10 #9cd58a
color11 #e6c384
color12 #7a88cf
color13 #d7729f
color14 #7bb0c0
color15 #a9b1d6
background #1f2335
selection_foreground #a9b1d6
cursor #a9b1d6
cursor_text_color #1f2335
foreground #a9b1d6
selection_background #4b517a
active_border_color #7a88cf
inactive_border_color #d7729f

active_tab_foreground   #1f2335
active_tab_background   #7a88cf
inactive_tab_foreground #c0caf5
inactive_tab_background #2c314a
cursor_trail_color      #c0caf5
