-- Generated by theme_render.py (eink light); edit the theme or this template, not the output.
-- Read by ~/.config/nvim/colors/desktop.lua (mini.base16) at startup and on SIGUSR1 from `theme`.
return {
	background = "light",
	palette = {
		base00 = "#cccccc", base01 = "#b8b8b8", base02 = "#aeaeae", base03 = "#686868",
		base04 = "#686868", base05 = "#333333", base06 = "#333333", base07 = "#333333",
		base08 = "#f85552", base09 = "#5e5e5e", base0A = "#333333", base0B = "#545454",
		base0C = "#727272", base0D = "#333333", base0E = "#545454", base0F = "#f85552",
	},
}
