" Generated by theme_render.py (eink light); edit the theme or this template, not the output.
" Sourced by ~/.vimrc at startup and whenever it changes. Backgrounds stay transparent.
set background=light
highlight clear
if exists('syntax_on') | syntax reset | endif
let g:colors_name = 'desktop'

hi Normal       guifg=#333333 guibg=NONE
hi NonText      guifg=#a4a4a4 guibg=NONE
hi EndOfBuffer  guifg=#cccccc guibg=NONE
hi LineNr       guifg=#a4a4a4 guibg=NONE
hi CursorLineNr guifg=#333333 guibg=NONE gui=bold
hi SignColumn   guibg=NONE
hi FoldColumn   guifg=#a4a4a4 guibg=NONE
hi Folded       guifg=#686868 guibg=#b8b8b8
hi CursorLine   guibg=#b8b8b8 gui=NONE cterm=NONE
hi CursorColumn guibg=#b8b8b8
hi ColorColumn  guibg=#b8b8b8
hi Visual       guibg=#aeaeae
hi Search       guifg=#cccccc guibg=#333333
hi IncSearch    guifg=#cccccc guibg=#5e5e5e
hi CurSearch    guifg=#cccccc guibg=#5e5e5e
hi MatchParen   guifg=#5e5e5e guibg=NONE gui=bold
hi VertSplit    guifg=#aeaeae guibg=NONE gui=NONE
hi WinSeparator guifg=#aeaeae guibg=NONE
hi StatusLine   guifg=#333333 guibg=#b8b8b8 gui=NONE
hi StatusLineNC guifg=#686868 guibg=NONE gui=NONE
hi TabLine      guifg=#686868 guibg=NONE gui=NONE
hi TabLineFill  guibg=NONE gui=NONE
hi TabLineSel   guifg=#333333 guibg=NONE gui=bold
hi Pmenu        guifg=#333333 guibg=#b8b8b8
hi PmenuSel     guifg=#cccccc guibg=#333333
hi PmenuSbar    guibg=#b8b8b8
hi PmenuThumb   guibg=#a4a4a4
hi WildMenu     guifg=#cccccc guibg=#333333
hi Directory    guifg=#333333
hi Title        guifg=#333333 gui=bold
hi ErrorMsg     guifg=#f85552 guibg=NONE
hi WarningMsg   guifg=#333333
hi ModeMsg      guifg=#545454 gui=bold
hi MoreMsg      guifg=#545454
hi Question     guifg=#333333
hi SpecialKey   guifg=#a4a4a4
hi DiffAdd      guifg=#545454 guibg=NONE
hi DiffChange   guifg=#333333 guibg=NONE
hi DiffDelete   guifg=#f85552 guibg=NONE
hi DiffText     guifg=#333333 guibg=NONE gui=bold
hi SpellBad     gui=undercurl guisp=#f85552
hi SpellCap     gui=undercurl guisp=#333333

hi Comment      guifg=#686868 gui=italic
hi Constant     guifg=#5e5e5e
hi String       guifg=#545454
hi Character    guifg=#545454
hi Number       guifg=#5e5e5e
hi Boolean      guifg=#5e5e5e
hi Identifier   guifg=#727272 gui=NONE
hi Function     guifg=#333333
hi Statement    guifg=#545454 gui=NONE
hi Operator     guifg=#727272
hi PreProc      guifg=#545454
hi Type         guifg=#333333 gui=NONE
hi Special      guifg=#727272
hi Delimiter    guifg=#686868
hi Underlined   guifg=#333333 gui=underline
hi Error        guifg=#f85552 guibg=NONE
hi Todo         guifg=#cccccc guibg=#333333 gui=bold
