-- Generated by theme_render.py (tokyonight light); edit the theme or this template, not the output.
-- Read by ~/.config/nvim/lua/config/theme.lua at startup and on SIGUSR1 (sent by `theme`).
return { colorscheme = "tokyonight-day", background = "light" }
