-- Generated by theme_render.py (tokyonight light); edit the theme or this template, not the output.
-- Read by ~/.config/nvim/colors/desktop.lua (mini.base16) at startup and on SIGUSR1 from `theme`.
return {
	background = "light",
	palette = {
		base00 = "#e1e2e7", base01 = "#c4c8da", base02 = "#b7c1e3", base03 = "#68709a",
		base04 = "#68709a", base05 = "#3760bf", base06 = "#3760bf", base07 = "#3760bf",
		base08 = "#f52a65", base09 = "#b15c00", base0A = "#8c6c3e", base0B = "#587539",
		base0C = "#007197", base0D = "#2e7de9", base0E = "#9854f1", base0F = "#ff4774",
	},
}
