-- Generated by theme_render.py (tokyonight light); edit the theme or this template, not the output.
-- Read by ~/.config/nvim/colors/desktop.lua (mini.base16) at startup and on SIGUSR1 from `theme`.
return {
	background = "light",
	palette = {
		base00 = "#e1e2e7", base01 = "#c4c8da", base02 = "#b7c1e3", base03 = "#68709a",
		base04 = "#68709a", base05 = "#3760bf", base06 = "#3760bf", base07 = "#3760bf",
		base08 = "#f52a65", base09 = "#b15c00", base0A = "#8c6c3e", base0B = "#587539",
		base0C = "#007197", base0D = "#2e7de9", base0E = "#9854f1", base0F = "#ff4774",
	},
	-- the theme's roles, for UI that base16 can't express (borders, which-key, lualine)
	ui = {
		bg = "#e1e2e7", fg = "#3760bf", fg_muted = "#68709a", surface = "#c4c8da", overlay = "#a8aecb",
		primary = "#2e7de9", on_primary = "#e1e2e7", secondary = "#9854f1", accent = "#b15c00",
		success = "#587539", warning = "#8c6c3e", error = "#f52a65",
		border = "#a8aecb", border_active = "#2e7de9", selection = "#b7c1e3",
	},
}
