" Generated by theme_render.py (tokyonight light); edit the theme or this template, not the output.
" Sourced by ~/.vimrc at startup and whenever it changes. Backgrounds stay transparent.
set background=light
highlight clear
if exists('syntax_on') | syntax reset | endif
let g:colors_name = 'desktop'

hi Normal       guifg=#3760bf guibg=NONE
hi NonText      guifg=#a8aecb guibg=NONE
hi EndOfBuffer  guifg=#e1e2e7 guibg=NONE
hi LineNr       guifg=#a8aecb guibg=NONE
hi CursorLineNr guifg=#2e7de9 guibg=NONE gui=bold
hi SignColumn   guibg=NONE
hi FoldColumn   guifg=#a8aecb guibg=NONE
hi Folded       guifg=#68709a guibg=#c4c8da
hi CursorLine   guibg=#c4c8da gui=NONE cterm=NONE
hi CursorColumn guibg=#c4c8da
hi ColorColumn  guibg=#c4c8da
hi Visual       guibg=#b7c1e3
hi Search       guifg=#e1e2e7 guibg=#8c6c3e
hi IncSearch    guifg=#e1e2e7 guibg=#b15c00
hi CurSearch    guifg=#e1e2e7 guibg=#b15c00
hi MatchParen   guifg=#b15c00 guibg=NONE gui=bold
hi VertSplit    guifg=#a8aecb guibg=NONE gui=NONE
hi WinSeparator guifg=#a8aecb guibg=NONE
hi StatusLine   guifg=#3760bf guibg=#c4c8da gui=NONE
hi StatusLineNC guifg=#68709a guibg=NONE gui=NONE
hi TabLine      guifg=#68709a guibg=NONE gui=NONE
hi TabLineFill  guibg=NONE gui=NONE
hi TabLineSel   guifg=#2e7de9 guibg=NONE gui=bold
hi Pmenu        guifg=#3760bf guibg=#c4c8da
hi PmenuSel     guifg=#e1e2e7 guibg=#2e7de9
hi PmenuSbar    guibg=#c4c8da
hi PmenuThumb   guibg=#a8aecb
hi WildMenu     guifg=#e1e2e7 guibg=#2e7de9
hi Directory    guifg=#2e7de9
hi Title        guifg=#2e7de9 gui=bold
hi ErrorMsg     guifg=#f52a65 guibg=NONE
hi WarningMsg   guifg=#8c6c3e
hi ModeMsg      guifg=#587539 gui=bold
hi MoreMsg      guifg=#587539
hi Question     guifg=#2e7de9
hi SpecialKey   guifg=#a8aecb
hi DiffAdd      guifg=#587539 guibg=NONE
hi DiffChange   guifg=#8c6c3e guibg=NONE
hi DiffDelete   guifg=#f52a65 guibg=NONE
hi DiffText     guifg=#2e7de9 guibg=NONE gui=bold
hi SpellBad     gui=undercurl guisp=#f52a65
hi SpellCap     gui=undercurl guisp=#8c6c3e

hi Comment      guifg=#68709a gui=italic
hi Constant     guifg=#b15c00
hi String       guifg=#587539
hi Character    guifg=#587539
hi Number       guifg=#b15c00
hi Boolean      guifg=#b15c00
hi Identifier   guifg=#007197 gui=NONE
hi Function     guifg=#2e7de9
hi Statement    guifg=#9854f1 gui=NONE
hi Operator     guifg=#007197
hi PreProc      guifg=#9854f1
hi Type         guifg=#8c6c3e gui=NONE
hi Special      guifg=#007197
hi Delimiter    guifg=#68709a
hi Underlined   guifg=#2e7de9 gui=underline
hi Error        guifg=#f52a65 guibg=NONE
hi Todo         guifg=#e1e2e7 guibg=#8c6c3e gui=bold
