-- Generated by theme_render.py (catppuccin light); edit the theme or this template, not the output.
-- Read by ~/.config/nvim/colors/desktop.lua (mini.base16) at startup and on SIGUSR1 from `theme`.
return {
	background = "light",
	palette = {
		base00 = "#eff1f5", base01 = "#ccd0da", base02 = "#acb0be", base03 = "#6c6f85",
		base04 = "#6c6f85", base05 = "#4c4f69", base06 = "#4c4f69", base07 = "#4c4f69",
		base08 = "#d20f39", base09 = "#fe640b", base0A = "#df8e1d", base0B = "#40a02b",
		base0C = "#179299", base0D = "#1e66f5", base0E = "#8839ef", base0F = "#d20f39",
	},
	-- the theme's roles, for UI that base16 can't express (borders, which-key, lualine)
	ui = {
		bg = "#eff1f5", fg = "#4c4f69", fg_muted = "#6c6f85", surface = "#ccd0da", overlay = "#bcc0cc",
		primary = "#1e66f5", on_primary = "#eff1f5", secondary = "#8839ef", accent = "#fe640b",
		success = "#40a02b", warning = "#df8e1d", error = "#d20f39",
		border = "#bcc0cc", border_active = "#1e66f5", selection = "#acb0be",
	},
}
