" Generated by theme_render.py (catppuccin light); edit the theme or this template, not the output.
" Sourced by ~/.vimrc at startup and whenever it changes. Backgrounds stay transparent.
set background=light
highlight clear
if exists('syntax_on') | syntax reset | endif
let g:colors_name = 'desktop'

hi Normal       guifg=#4c4f69 guibg=NONE
hi NonText      guifg=#bcc0cc guibg=NONE
hi EndOfBuffer  guifg=#eff1f5 guibg=NONE
hi LineNr       guifg=#bcc0cc guibg=NONE
hi CursorLineNr guifg=#1e66f5 guibg=NONE gui=bold
hi SignColumn   guibg=NONE
hi FoldColumn   guifg=#bcc0cc guibg=NONE
hi Folded       guifg=#6c6f85 guibg=#ccd0da
hi CursorLine   guibg=#ccd0da gui=NONE cterm=NONE
hi CursorColumn guibg=#ccd0da
hi ColorColumn  guibg=#ccd0da
hi Visual       guibg=#acb0be
hi Search       guifg=#eff1f5 guibg=#df8e1d
hi IncSearch    guifg=#eff1f5 guibg=#fe640b
hi CurSearch    guifg=#eff1f5 guibg=#fe640b
hi MatchParen   guifg=#fe640b guibg=NONE gui=bold
hi VertSplit    guifg=#bcc0cc guibg=NONE gui=NONE
hi WinSeparator guifg=#bcc0cc guibg=NONE
hi StatusLine   guifg=#4c4f69 guibg=#ccd0da gui=NONE
hi StatusLineNC guifg=#6c6f85 guibg=NONE gui=NONE
hi TabLine      guifg=#6c6f85 guibg=NONE gui=NONE
hi TabLineFill  guibg=NONE gui=NONE
hi TabLineSel   guifg=#1e66f5 guibg=NONE gui=bold
hi Pmenu        guifg=#4c4f69 guibg=#ccd0da
hi PmenuSel     guifg=#eff1f5 guibg=#1e66f5
hi PmenuSbar    guibg=#ccd0da
hi PmenuThumb   guibg=#bcc0cc
hi WildMenu     guifg=#eff1f5 guibg=#1e66f5
hi Directory    guifg=#1e66f5
hi Title        guifg=#1e66f5 gui=bold
hi ErrorMsg     guifg=#d20f39 guibg=NONE
hi WarningMsg   guifg=#df8e1d
hi ModeMsg      guifg=#40a02b gui=bold
hi MoreMsg      guifg=#40a02b
hi Question     guifg=#1e66f5
hi SpecialKey   guifg=#bcc0cc
hi DiffAdd      guifg=#40a02b guibg=NONE
hi DiffChange   guifg=#df8e1d guibg=NONE
hi DiffDelete   guifg=#d20f39 guibg=NONE
hi DiffText     guifg=#1e66f5 guibg=NONE gui=bold
hi SpellBad     gui=undercurl guisp=#d20f39
hi SpellCap     gui=undercurl guisp=#df8e1d

hi Comment      guifg=#6c6f85 gui=italic
hi Constant     guifg=#fe640b
hi String       guifg=#40a02b
hi Character    guifg=#40a02b
hi Number       guifg=#fe640b
hi Boolean      guifg=#fe640b
hi Identifier   guifg=#179299 gui=NONE
hi Function     guifg=#1e66f5
hi Statement    guifg=#8839ef gui=NONE
hi Operator     guifg=#179299
hi PreProc      guifg=#8839ef
hi Type         guifg=#df8e1d gui=NONE
hi Special      guifg=#179299
hi Delimiter    guifg=#6c6f85
hi Underlined   guifg=#1e66f5 gui=underline
hi Error        guifg=#d20f39 guibg=NONE
hi Todo         guifg=#eff1f5 guibg=#df8e1d gui=bold
