-- Generated by theme_render.py (gruvbox dark); edit the theme or this template, not the output.
-- Read by ~/.config/nvim/lua/config/theme.lua at startup and on SIGUSR1 (sent by `theme`).
return { colorscheme = "gruvbox", background = "dark" }
