" Generated by theme_render.py (gruvbox dark); edit the theme or this template, not the output.
" Sourced by ~/.vimrc at startup and whenever it changes. Backgrounds stay transparent.
set background=dark
highlight clear
if exists('syntax_on') | syntax reset | endif
let g:colors_name = 'desktop'

hi Normal       guifg=#ebdbb2 guibg=NONE
hi NonText      guifg=#504945 guibg=NONE
hi EndOfBuffer  guifg=#282828 guibg=NONE
hi LineNr       guifg=#504945 guibg=NONE
hi CursorLineNr guifg=#fabd2f guibg=NONE gui=bold
hi SignColumn   guibg=NONE
hi FoldColumn   guifg=#504945 guibg=NONE
hi Folded       guifg=#a89984 guibg=#3c3836
hi CursorLine   guibg=#3c3836 gui=NONE cterm=NONE
hi CursorColumn guibg=#3c3836
hi ColorColumn  guibg=#3c3836
hi Visual       guibg=#504945
hi Search       guifg=#282828 guibg=#fabd2f
hi IncSearch    guifg=#282828 guibg=#fe8019
hi CurSearch    guifg=#282828 guibg=#fe8019
hi MatchParen   guifg=#fe8019 guibg=NONE gui=bold
hi VertSplit    guifg=#504945 guibg=NONE gui=NONE
hi WinSeparator guifg=#504945 guibg=NONE
hi StatusLine   guifg=#ebdbb2 guibg=#3c3836 gui=NONE
hi StatusLineNC guifg=#a89984 guibg=NONE gui=NONE
hi TabLine      guifg=#a89984 guibg=NONE gui=NONE
hi TabLineFill  guibg=NONE gui=NONE
hi TabLineSel   guifg=#fabd2f guibg=NONE gui=bold
hi Pmenu        guifg=#ebdbb2 guibg=#3c3836
hi PmenuSel     guifg=#282828 guibg=#fabd2f
hi PmenuSbar    guibg=#3c3836
hi PmenuThumb   guibg=#504945
hi WildMenu     guifg=#282828 guibg=#fabd2f
hi Directory    guifg=#fabd2f
hi Title        guifg=#fabd2f gui=bold
hi ErrorMsg     guifg=#fb4934 guibg=NONE
hi WarningMsg   guifg=#fabd2f
hi ModeMsg      guifg=#b8bb26 gui=bold
hi MoreMsg      guifg=#b8bb26
hi Question     guifg=#fabd2f
hi SpecialKey   guifg=#504945
hi DiffAdd      guifg=#b8bb26 guibg=NONE
hi DiffChange   guifg=#fabd2f guibg=NONE
hi DiffDelete   guifg=#fb4934 guibg=NONE
hi DiffText     guifg=#fabd2f guibg=NONE gui=bold
hi SpellBad     gui=undercurl guisp=#fb4934
hi SpellCap     gui=undercurl guisp=#fabd2f

hi Comment      guifg=#a89984 gui=italic
hi Constant     guifg=#fe8019
hi String       guifg=#b8bb26
hi Character    guifg=#b8bb26
hi Number       guifg=#fe8019
hi Boolean      guifg=#fe8019
hi Identifier   guifg=#689d6a gui=NONE
hi Function     guifg=#fabd2f
hi Statement    guifg=#8ec07c gui=NONE
hi Operator     guifg=#689d6a
hi PreProc      guifg=#8ec07c
hi Type         guifg=#fabd2f gui=NONE
hi Special      guifg=#689d6a
hi Delimiter    guifg=#a89984
hi Underlined   guifg=#fabd2f gui=underline
hi Error        guifg=#fb4934 guibg=NONE
hi Todo         guifg=#282828 guibg=#fabd2f gui=bold
