-- Generated by theme_render.py (gruvbox light); edit the theme or this template, not the output.
-- Read by ~/.config/nvim/colors/desktop.lua (mini.base16) at startup and on SIGUSR1 from `theme`.
return {
	background = "light",
	palette = {
		base00 = "#fbf1c7", base01 = "#ebdbb2", base02 = "#d5c4a1", base03 = "#7c6f64",
		base04 = "#7c6f64", base05 = "#3c3836", base06 = "#3c3836", base07 = "#3c3836",
		base08 = "#9d0006", base09 = "#af3a03", base0A = "#b57614", base0B = "#79740e",
		base0C = "#689d6a", base0D = "#b57614", base0E = "#427b58", base0F = "#9d0006",
	},
}
