" Generated by theme_render.py (gruvbox light); edit the theme or this template, not the output.
" Sourced by ~/.vimrc at startup and whenever it changes. Backgrounds stay transparent.
set background=light
highlight clear
if exists('syntax_on') | syntax reset | endif
let g:colors_name = 'desktop'

hi Normal       guifg=#3c3836 guibg=NONE
hi NonText      guifg=#d5c4a1 guibg=NONE
hi EndOfBuffer  guifg=#fbf1c7 guibg=NONE
hi LineNr       guifg=#d5c4a1 guibg=NONE
hi CursorLineNr guifg=#b57614 guibg=NONE gui=bold
hi SignColumn   guibg=NONE
hi FoldColumn   guifg=#d5c4a1 guibg=NONE
hi Folded       guifg=#7c6f64 guibg=#ebdbb2
hi CursorLine   guibg=#ebdbb2 gui=NONE cterm=NONE
hi CursorColumn guibg=#ebdbb2
hi ColorColumn  guibg=#ebdbb2
hi Visual       guibg=#d5c4a1
hi Search       guifg=#fbf1c7 guibg=#b57614
hi IncSearch    guifg=#fbf1c7 guibg=#af3a03
hi CurSearch    guifg=#fbf1c7 guibg=#af3a03
hi MatchParen   guifg=#af3a03 guibg=NONE gui=bold
hi VertSplit    guifg=#d5c4a1 guibg=NONE gui=NONE
hi WinSeparator guifg=#d5c4a1 guibg=NONE
hi StatusLine   guifg=#3c3836 guibg=#ebdbb2 gui=NONE
hi StatusLineNC guifg=#7c6f64 guibg=NONE gui=NONE
hi TabLine      guifg=#7c6f64 guibg=NONE gui=NONE
hi TabLineFill  guibg=NONE gui=NONE
hi TabLineSel   guifg=#b57614 guibg=NONE gui=bold
hi Pmenu        guifg=#3c3836 guibg=#ebdbb2
hi PmenuSel     guifg=#fbf1c7 guibg=#b57614
hi PmenuSbar    guibg=#ebdbb2
hi PmenuThumb   guibg=#d5c4a1
hi WildMenu     guifg=#fbf1c7 guibg=#b57614
hi Directory    guifg=#b57614
hi Title        guifg=#b57614 gui=bold
hi ErrorMsg     guifg=#9d0006 guibg=NONE
hi WarningMsg   guifg=#b57614
hi ModeMsg      guifg=#79740e gui=bold
hi MoreMsg      guifg=#79740e
hi Question     guifg=#b57614
hi SpecialKey   guifg=#d5c4a1
hi DiffAdd      guifg=#79740e guibg=NONE
hi DiffChange   guifg=#b57614 guibg=NONE
hi DiffDelete   guifg=#9d0006 guibg=NONE
hi DiffText     guifg=#b57614 guibg=NONE gui=bold
hi SpellBad     gui=undercurl guisp=#9d0006
hi SpellCap     gui=undercurl guisp=#b57614

hi Comment      guifg=#7c6f64 gui=italic
hi Constant     guifg=#af3a03
hi String       guifg=#79740e
hi Character    guifg=#79740e
hi Number       guifg=#af3a03
hi Boolean      guifg=#af3a03
hi Identifier   guifg=#689d6a gui=NONE
hi Function     guifg=#b57614
hi Statement    guifg=#427b58 gui=NONE
hi Operator     guifg=#689d6a
hi PreProc      guifg=#427b58
hi Type         guifg=#b57614 gui=NONE
hi Special      guifg=#689d6a
hi Delimiter    guifg=#7c6f64
hi Underlined   guifg=#b57614 gui=underline
hi Error        guifg=#9d0006 guibg=NONE
hi Todo         guifg=#fbf1c7 guibg=#b57614 gui=bold
