;;; autothemer-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from autothemer.el

(autoload 'autothemer-deftheme "autothemer" "\
Define a theme NAME with description DESCRIPTION.
A color PALETTE can be used to define `let*'-like
bindings within both the REDUCED-SPECS and the BODY.

(fn NAME DESCRIPTION PALETTE REDUCED-SPECS &rest BODY)" nil t)
(autoload 'autothemer-insert-missing-face "autothemer" "\
Insert a face spec template for an unthemed face.
An approximate color from the palette will be used for
color attributes." t)
(autoload 'autothemer-insert-missing-faces "autothemer" "\
Insert face spec templates for unthemed faces matching REGEXP.
An error is shown when no current theme is available.

(fn &optional REGEXP)" t)
(autoload 'autothemer-generate-templates-filtered "autothemer" "\
Autogenerate customizations for unthemed faces matching REGEXP.

Calls `autothemer-generate-templates' after user provides REGEXP interactively.

(fn REGEXP)" t)
(autoload 'autothemer-generate-templates "autothemer" "\
Autogenerate customizations for unthemed faces (optionally by REGEXP).

Generate customizations that approximate current face definitions using the
nearest colors in the color palette of `autothemer-current-theme'.

An error is shown when no current theme is available.

(fn &optional REGEXP)" t)
(register-definition-prefixes "autothemer" '("autothemer-"))

;;; End of scraped data

(provide 'autothemer-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; autothemer-autoloads.el ends here
