-- Generated by theme_render.py (catppuccin dark); edit the theme or this template, not the output.
-- Read by ~/.config/nvim/colors/desktop.lua (mini.base16) at startup and on SIGUSR1 from `theme`.
return {
	background = "dark",
	palette = {
		base00 = "#1e1e2e", base01 = "#313244", base02 = "#585b70", base03 = "#a6adc8",
		base04 = "#a6adc8", base05 = "#cdd6f4", base06 = "#cdd6f4", base07 = "#cdd6f4",
		base08 = "#f38ba8", base09 = "#fab387", base0A = "#f9e2af", base0B = "#a6e3a1",
		base0C = "#94e2d5", base0D = "#89b4fa", base0E = "#cba6f7", base0F = "#f38ba8",
	},
}
