" Generated by theme_render.py (catppuccin dark); edit the theme or this template, not the output.
" Sourced by ~/.vimrc at startup and whenever it changes. Backgrounds stay transparent.
set background=dark
highlight clear
if exists('syntax_on') | syntax reset | endif
let g:colors_name = 'desktop'

hi Normal       guifg=#cdd6f4 guibg=NONE
hi NonText      guifg=#45475a guibg=NONE
hi EndOfBuffer  guifg=#1e1e2e guibg=NONE
hi LineNr       guifg=#45475a guibg=NONE
hi CursorLineNr guifg=#89b4fa guibg=NONE gui=bold
hi SignColumn   guibg=NONE
hi FoldColumn   guifg=#45475a guibg=NONE
hi Folded       guifg=#a6adc8 guibg=#313244
hi CursorLine   guibg=#313244 gui=NONE cterm=NONE
hi CursorColumn guibg=#313244
hi ColorColumn  guibg=#313244
hi Visual       guibg=#585b70
hi Search       guifg=#1e1e2e guibg=#f9e2af
hi IncSearch    guifg=#1e1e2e guibg=#fab387
hi CurSearch    guifg=#1e1e2e guibg=#fab387
hi MatchParen   guifg=#fab387 guibg=NONE gui=bold
hi VertSplit    guifg=#45475a guibg=NONE gui=NONE
hi WinSeparator guifg=#45475a guibg=NONE
hi StatusLine   guifg=#cdd6f4 guibg=#313244 gui=NONE
hi StatusLineNC guifg=#a6adc8 guibg=NONE gui=NONE
hi TabLine      guifg=#a6adc8 guibg=NONE gui=NONE
hi TabLineFill  guibg=NONE gui=NONE
hi TabLineSel   guifg=#89b4fa guibg=NONE gui=bold
hi Pmenu        guifg=#cdd6f4 guibg=#313244
hi PmenuSel     guifg=#1e1e2e guibg=#89b4fa
hi PmenuSbar    guibg=#313244
hi PmenuThumb   guibg=#45475a
hi WildMenu     guifg=#1e1e2e guibg=#89b4fa
hi Directory    guifg=#89b4fa
hi Title        guifg=#89b4fa gui=bold
hi ErrorMsg     guifg=#f38ba8 guibg=NONE
hi WarningMsg   guifg=#f9e2af
hi ModeMsg      guifg=#a6e3a1 gui=bold
hi MoreMsg      guifg=#a6e3a1
hi Question     guifg=#89b4fa
hi SpecialKey   guifg=#45475a
hi DiffAdd      guifg=#a6e3a1 guibg=NONE
hi DiffChange   guifg=#f9e2af guibg=NONE
hi DiffDelete   guifg=#f38ba8 guibg=NONE
hi DiffText     guifg=#89b4fa guibg=NONE gui=bold
hi SpellBad     gui=undercurl guisp=#f38ba8
hi SpellCap     gui=undercurl guisp=#f9e2af

hi Comment      guifg=#a6adc8 gui=italic
hi Constant     guifg=#fab387
hi String       guifg=#a6e3a1
hi Character    guifg=#a6e3a1
hi Number       guifg=#fab387
hi Boolean      guifg=#fab387
hi Identifier   guifg=#94e2d5 gui=NONE
hi Function     guifg=#89b4fa
hi Statement    guifg=#cba6f7 gui=NONE
hi Operator     guifg=#94e2d5
hi PreProc      guifg=#cba6f7
hi Type         guifg=#f9e2af gui=NONE
hi Special      guifg=#94e2d5
hi Delimiter    guifg=#a6adc8
hi Underlined   guifg=#89b4fa gui=underline
hi Error        guifg=#f38ba8 guibg=NONE
hi Todo         guifg=#1e1e2e guibg=#f9e2af gui=bold
