return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	dependencies = {
		"nvim-treesitter/nvim-treesitter-textobjects",
	},
	config = function()
		require("nvim-treesitter").setup({
			ensure_installed = {
				"bash",
				"c",
				"lua",
				"vim",
				"vimdoc",
				"query",
				"regex",
				"python",
				"javascript",
				"typescript",
				"tsx",
				"go",
				"rust",
				"cpp",
				"java",
				"ruby",
				"php",
				"elixir",
				"haskell",
				"scala",
				"html",
				"css",
				"json",
				"yaml",
				"toml",
				"markdown",
				"markdown_inline",
				"vue",
				"svelte",
				"graphql",
				"dockerfile",
				"cmake",
				"make",
				"ini",
				"xml",
				"sql",
				"csv",
				"perl",
				"fish",
				"luadoc",
				"diff",
				"zig",
			},
			auto_install = true,
			highlight = {
				enable = true,
				additional_vim_regex_highlighting = { "ruby" },
			},
			indent = { enable = true, disable = { "ruby" } },
			incremental_selection = {
				enable = true,
				keymaps = {
					init_selection = "<M-space>",
					node_incremental = "<M-space>",
					scope_incremental = false,
					node_decremental = "<Backspace>",
				},
			},
			textobjects = {
				select = {
					enable = true,
					lookahead = true,
					keymaps = {
						["af"] = "@function.outer",
						["if"] = "@function.inner",
						["ac"] = "@class.outer",
						["ic"] = "@class.inner",
					},
				},
				swap = {
					enable = true,
					swap_next = { ["<leader>xs"] = "@parameter.inner" },
					swap_previous = { ["<leader>xS"] = "@parameter.inner" },
				},
			},
		})
	end,
}
