bind = $mainMod, return, exec, $terminal
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, B, exec, $browser
bind = $mainMod, D, exec, $menu
# bind = $mainMod, C, exec, hyprlock
# bind = $mainMod, P, exec, wlogout

bind =  $mainMod SHIFT, t, exec, noctalia msg panel-toggle 2SSK/todoist:panel
bind =  $mainMod SHIFT, c, exec, noctalia msg panel-toggle clipboard
bind =  $mainMod SHIFT, n, exec, noctalia msg panel-toggle noctalia/notes:panel
bind =  $mainMod SHIFT, s, exec, noctalia msg settings-toggle
