# Switch preset column width 
bind = SUPER, r, layoutmsg, colresize +conf
bind = SUPER SHIFT, r, layoutmsg, colresize -conf

# Maximize column 
bind = SUPER, f, layoutmsg, togglefit

# Center column 
bind = SUPER, c, layoutmsg, fit active


# Swap column left/right (like Niri Mod+S)
bind = SUPER, s, layoutmsg, swapcol r
# bind = SUPER SHIFT, s, layoutmsg, swapcol l

# Focus first/last column
bind = SUPER, home, layoutmsg, focus l
bind = SUPER, end, layoutmsg, focus r

# Move window left/down/up/right 
bind = SUPER SHIFT, h, movewindow, l
bind = SUPER SHIFT, j, movewindow, d
bind = SUPER SHIFT, k, movewindow, u
bind = SUPER SHIFT, l, movewindow, r
