bind = $mainMod, h, movefocus, l:smart
bind = $mainMod, l, movefocus, r:smart
bind = $mainMod, k, movefocus, u:smart
bind = $mainMod, j, movefocus, d:smart

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
