-- Generated by theme_render.py (eink dark); edit the theme or this template, not the output.
-- Read by ~/.config/nvim/colors/desktop.lua (mini.base16) at startup and on SIGUSR1 from `theme`.
return {
	background = "dark",
	palette = {
		base00 = "#333333", base01 = "#4a4a4a", base02 = "#545454", base03 = "#909090",
		base04 = "#909090", base05 = "#c2c2c2", base06 = "#c2c2c2", base07 = "#c2c2c2",
		base08 = "#e67e80", base09 = "#a4a4a4", base0A = "#cccccc", base0B = "#aeaeae",
		base0C = "#909090", base0D = "#cccccc", base0E = "#aeaeae", base0F = "#e67e80",
	},
}
