" Generated by theme_render.py (eink dark); edit the theme or this template, not the output.
" Sourced by ~/.vimrc at startup and whenever it changes. Backgrounds stay transparent.
set background=dark
highlight clear
if exists('syntax_on') | syntax reset | endif
let g:colors_name = 'desktop'

hi Normal       guifg=#c2c2c2 guibg=NONE
hi NonText      guifg=#5e5e5e guibg=NONE
hi EndOfBuffer  guifg=#333333 guibg=NONE
hi LineNr       guifg=#5e5e5e guibg=NONE
hi CursorLineNr guifg=#cccccc guibg=NONE gui=bold
hi SignColumn   guibg=NONE
hi FoldColumn   guifg=#5e5e5e guibg=NONE
hi Folded       guifg=#909090 guibg=#4a4a4a
hi CursorLine   guibg=#4a4a4a gui=NONE cterm=NONE
hi CursorColumn guibg=#4a4a4a
hi ColorColumn  guibg=#4a4a4a
hi Visual       guibg=#545454
hi Search       guifg=#333333 guibg=#cccccc
hi IncSearch    guifg=#333333 guibg=#a4a4a4
hi CurSearch    guifg=#333333 guibg=#a4a4a4
hi MatchParen   guifg=#a4a4a4 guibg=NONE gui=bold
hi VertSplit    guifg=#545454 guibg=NONE gui=NONE
hi WinSeparator guifg=#545454 guibg=NONE
hi StatusLine   guifg=#c2c2c2 guibg=#4a4a4a gui=NONE
hi StatusLineNC guifg=#909090 guibg=NONE gui=NONE
hi TabLine      guifg=#909090 guibg=NONE gui=NONE
hi TabLineFill  guibg=NONE gui=NONE
hi TabLineSel   guifg=#cccccc guibg=NONE gui=bold
hi Pmenu        guifg=#c2c2c2 guibg=#4a4a4a
hi PmenuSel     guifg=#333333 guibg=#cccccc
hi PmenuSbar    guibg=#4a4a4a
hi PmenuThumb   guibg=#5e5e5e
hi WildMenu     guifg=#333333 guibg=#cccccc
hi Directory    guifg=#cccccc
hi Title        guifg=#cccccc gui=bold
hi ErrorMsg     guifg=#e67e80 guibg=NONE
hi WarningMsg   guifg=#cccccc
hi ModeMsg      guifg=#aeaeae gui=bold
hi MoreMsg      guifg=#aeaeae
hi Question     guifg=#cccccc
hi SpecialKey   guifg=#5e5e5e
hi DiffAdd      guifg=#aeaeae guibg=NONE
hi DiffChange   guifg=#cccccc guibg=NONE
hi DiffDelete   guifg=#e67e80 guibg=NONE
hi DiffText     guifg=#cccccc guibg=NONE gui=bold
hi SpellBad     gui=undercurl guisp=#e67e80
hi SpellCap     gui=undercurl guisp=#cccccc

hi Comment      guifg=#909090 gui=italic
hi Constant     guifg=#a4a4a4
hi String       guifg=#aeaeae
hi Character    guifg=#aeaeae
hi Number       guifg=#a4a4a4
hi Boolean      guifg=#a4a4a4
hi Identifier   guifg=#909090 gui=NONE
hi Function     guifg=#cccccc
hi Statement    guifg=#aeaeae gui=NONE
hi Operator     guifg=#909090
hi PreProc      guifg=#aeaeae
hi Type         guifg=#cccccc gui=NONE
hi Special      guifg=#909090
hi Delimiter    guifg=#909090
hi Underlined   guifg=#cccccc gui=underline
hi Error        guifg=#e67e80 guibg=NONE
hi Todo         guifg=#333333 guibg=#cccccc gui=bold
