bindsym $mod+Return exec $term
bindsym $mod+d exec --no-startup-id $menu
bindsym $mod+Tab exec --no-startup-id rofi -show window
bindsym $mod+q kill

bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right
bindsym $mod+Shift+h move left
bindsym $mod+Shift+j move down
bindsym $mod+Shift+k move up
bindsym $mod+Shift+l move right
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Left move window to output left
bindsym $mod+Shift+Right move window to output right

bindsym $mod+f fullscreen toggle
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split
bindsym $mod+z split h
bindsym $mod+v split v
bindsym $mod+a focus parent
bindsym $mod+Shift+space floating toggle
bindsym $mod+space focus mode_toggle

bindsym $mod+Shift+Return move scratchpad
bindsym $mod+minus scratchpad show

bindsym $mod+Shift+c reload
bindsym $mod+Shift+r restart
