;;; nerd-icons-corfu-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from nerd-icons-corfu.el

(autoload 'nerd-icons-corfu-formatter "nerd-icons-corfu" "\
A margin formatter for Corfu, adding icons.

It receives METADATA, ignores it, and outputs a function that takes a candidate
and returns the icon.

(fn _)")
(register-definition-prefixes "nerd-icons-corfu" '("nerd-icons-corfu-"))

;;; End of scraped data

(provide 'nerd-icons-corfu-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; nerd-icons-corfu-autoloads.el ends here
