;;; dashboard-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from dashboard.el

(autoload 'dashboard-open "dashboard" "\
Open (or refresh) the *dashboard* buffer.

(fn &rest _)" t)
(autoload 'dashboard-setup-startup-hook "dashboard" "\
Setup post initialization hooks unless a command line argument is provided.")
(register-definition-prefixes "dashboard" '("dashboard-"))


;;; Generated autoloads from dashboard-widgets.el

(register-definition-prefixes "dashboard-widgets" '("dashboard-" "recentf-list"))

;;; End of scraped data

(provide 'dashboard-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; dashboard-autoloads.el ends here
