-- Generated by theme_render.py (rosepine light); edit the theme or this template, not the output.
-- Read by ~/.config/nvim/lua/config/theme.lua at startup and on SIGUSR1 (sent by `theme`).
return { colorscheme = "rose-pine-dawn", background = "light" }
