-- Generated by theme_render.py (rosepine light); edit the theme or this template, not the output.
-- Read by ~/.config/nvim/colors/desktop.lua (mini.base16) at startup and on SIGUSR1 from `theme`.
return {
	background = "light",
	palette = {
		base00 = "#faf4ed", base01 = "#f2e9e1", base02 = "#dfdad9", base03 = "#797593",
		base04 = "#797593", base05 = "#575279", base06 = "#575279", base07 = "#575279",
		base08 = "#b4637a", base09 = "#d7827e", base0A = "#ea9d34", base0B = "#56949f",
		base0C = "#d7827e", base0D = "#907aa9", base0E = "#286983", base0F = "#b4637a",
	},
	-- the theme's roles, for UI that base16 can't express (borders, which-key, lualine)
	ui = {
		bg = "#faf4ed", fg = "#575279", fg_muted = "#797593", surface = "#f2e9e1", overlay = "#dfdad9",
		primary = "#907aa9", on_primary = "#faf4ed", secondary = "#286983", accent = "#d7827e",
		success = "#56949f", warning = "#ea9d34", error = "#b4637a",
		border = "#cecacd", border_active = "#907aa9", selection = "#dfdad9",
	},
}
