-- Generated by theme_render.py (rosepine light); edit the theme or this template, not the output.
-- Read by ~/.config/nvim/colors/desktop.lua (mini.base16) at startup and on SIGUSR1 from `theme`.
return {
	background = "light",
	palette = {
		base00 = "#faf4ed", base01 = "#f2e9e1", base02 = "#dfdad9", base03 = "#797593",
		base04 = "#797593", base05 = "#575279", base06 = "#575279", base07 = "#575279",
		base08 = "#b4637a", base09 = "#d7827e", base0A = "#ea9d34", base0B = "#56949f",
		base0C = "#d7827e", base0D = "#907aa9", base0E = "#286983", base0F = "#b4637a",
	},
}
