" Generated by theme_render.py (rosepine light); edit the theme or this template, not the output.
" Sourced by ~/.vimrc at startup and whenever it changes. Backgrounds stay transparent.
set background=light
highlight clear
if exists('syntax_on') | syntax reset | endif
let g:colors_name = 'desktop'

hi Normal       guifg=#575279 guibg=NONE
hi NonText      guifg=#dfdad9 guibg=NONE
hi EndOfBuffer  guifg=#faf4ed guibg=NONE
hi LineNr       guifg=#dfdad9 guibg=NONE
hi CursorLineNr guifg=#907aa9 guibg=NONE gui=bold
hi SignColumn   guibg=NONE
hi FoldColumn   guifg=#dfdad9 guibg=NONE
hi Folded       guifg=#797593 guibg=#f2e9e1
hi CursorLine   guibg=#f2e9e1 gui=NONE cterm=NONE
hi CursorColumn guibg=#f2e9e1
hi ColorColumn  guibg=#f2e9e1
hi Visual       guibg=#dfdad9
hi Search       guifg=#faf4ed guibg=#ea9d34
hi IncSearch    guifg=#faf4ed guibg=#d7827e
hi CurSearch    guifg=#faf4ed guibg=#d7827e
hi MatchParen   guifg=#d7827e guibg=NONE gui=bold
hi VertSplit    guifg=#cecacd guibg=NONE gui=NONE
hi WinSeparator guifg=#cecacd guibg=NONE
hi StatusLine   guifg=#575279 guibg=#f2e9e1 gui=NONE
hi StatusLineNC guifg=#797593 guibg=NONE gui=NONE
hi TabLine      guifg=#797593 guibg=NONE gui=NONE
hi TabLineFill  guibg=NONE gui=NONE
hi TabLineSel   guifg=#907aa9 guibg=NONE gui=bold
hi Pmenu        guifg=#575279 guibg=#f2e9e1
hi PmenuSel     guifg=#faf4ed guibg=#907aa9
hi PmenuSbar    guibg=#f2e9e1
hi PmenuThumb   guibg=#dfdad9
hi WildMenu     guifg=#faf4ed guibg=#907aa9
hi Directory    guifg=#907aa9
hi Title        guifg=#907aa9 gui=bold
hi ErrorMsg     guifg=#b4637a guibg=NONE
hi WarningMsg   guifg=#ea9d34
hi ModeMsg      guifg=#56949f gui=bold
hi MoreMsg      guifg=#56949f
hi Question     guifg=#907aa9
hi SpecialKey   guifg=#dfdad9
hi DiffAdd      guifg=#56949f guibg=NONE
hi DiffChange   guifg=#ea9d34 guibg=NONE
hi DiffDelete   guifg=#b4637a guibg=NONE
hi DiffText     guifg=#907aa9 guibg=NONE gui=bold
hi SpellBad     gui=undercurl guisp=#b4637a
hi SpellCap     gui=undercurl guisp=#ea9d34

hi Comment      guifg=#797593 gui=italic
hi Constant     guifg=#d7827e
hi String       guifg=#56949f
hi Character    guifg=#56949f
hi Number       guifg=#d7827e
hi Boolean      guifg=#d7827e
hi Identifier   guifg=#d7827e gui=NONE
hi Function     guifg=#907aa9
hi Statement    guifg=#286983 gui=NONE
hi Operator     guifg=#d7827e
hi PreProc      guifg=#286983
hi Type         guifg=#ea9d34 gui=NONE
hi Special      guifg=#d7827e
hi Delimiter    guifg=#797593
hi Underlined   guifg=#907aa9 gui=underline
hi Error        guifg=#b4637a guibg=NONE
hi Todo         guifg=#faf4ed guibg=#ea9d34 gui=bold
