[bar.main]
position = "top"
thickness = 38
background_opacity = 0.75
radius = 12
margin_ends = 18
margin_edge = 18
padding = 5
widget_spacing = 6
scale = 1.2
shadow = true
auto_hide = false
reserve_space = true
capsule = false
hover_highlight = true
font_family = "JetBrainsMono Nerd Font Mono"

start = ["workspaces", "cpu", "mem", "temp"]
center = ["clock"]
end = ["clipboard", "battery", "notifications", "session"]

[bar.main.dead_zone]
command = "noctalia msg launcher toggle"

[widget.workspaces]
display = "none"
minimal = false
pill_scale = 0.8
active_pill_size = 2.2
inactive_pill_size = 1.0
focused_color = "primary"
occupied_color = "secondary"
empty_color = "secondary"
focused_output_only = false
labels_only_when_occupied = false
hide_when_empty = true

[widget.clock]
format = "{:%-I:%M %p %a, %b %d}"
vertical_format = "{:%H\n%M}"
tooltip_format = "{:%H:%M %a, %b %d}"

[widget.cpu]
type = "sysmon"
stat = "cpu_usage"
display = "text"
show_label = true

[widget.mem]
type = "sysmon"
stat = "ram_pct"
display = "text"
show_label = true

[widget.temp]
type = "sysmon"
stat = "cpu_temp"
display = "text"
show_label = true

[widget.battery]
type = "battery"
device = "auto"
display_mode = "icon"
show_label = true

[widget.notifications]
hide_when_no_unread = false

[widget.launcher]
glyph = "search"

[widget.session]
glyph = "power"

[widget.control-center]
glyph = "noctalia"
