[notification]
enable_daemon = true
show_app_name = true
show_actions = true
layer = "top"
scale = 1.0
background_opacity = 1.0
offset_x = 20
offset_y = 8

[osd]
position = "top_right"
position_vertical = "top_center"
orientation = "horizontal"
scale = 1.0
background_opacity = 0.97
offset_x = 20
offset_y = 8

[osd.kinds]
volume = true
volume_output = true
volume_input = true
brightness = true
wifi = true
bluetooth = true
power_profile = true
caffeine = true
nightlight = true
dnd = true
lock_keys = true
keyboard_layout = true
privacy = true

[audio]
enable_overdrive = false
enable_sounds = false
sound_volume = 0.5

[brightness]
enable_ddcutil = false

[nightlight]
enabled = false
force = false
temperature_day = 6500
temperature_night = 4000

[location]
auto_locate = true
name = "Bengaluru"

[weather]
enabled = true
refresh_minutes = 30
unit = "celsius"
effects = true

[idle.behavior.lock]
timeout = 660
command = "noctalia:session lock"
enabled = true

[idle.behavior.screen-off]
timeout = 600
command = "noctalia:dpms-off"
resume_command = "noctalia:dpms-on"
enabled = true
