[wallpaper]
enabled = true
fill_mode = "crop"
fill_color = ""
transition = ["fade", "wipe", "disc", "stripes", "zoom", "honeycomb"]
transition_duration = 1500
edge_smoothness = 0.3
transition_on_startup = false
directory = "~/Pictures/Wallpapers"

[wallpaper.default]
path = ""

[wallpaper.automation]
enabled = false
interval_minutes = 0
order = "random"
recursive = true
