[hooks]
battery_low_percent_threshold = 0

[theme.templates]
enable_builtin_templates = true
builtin_ids = []
enable_community_templates = true
community_ids = []

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "wallpaper"

[[control_center.shortcuts]]
type = "notification"

[[control_center.shortcuts]]
type = "nightlight"

[[control_center.shortcuts]]
type = "session"
